#!/bin/bash
# 重新编译并测试动态YOLO类别切换

echo "========== 步骤 1: 激活 drone 环境 =========="
echo "请运行: conda activate drone"
echo ""
echo "========== 步骤 2: 清理旧的编译文件 =========="
echo "cd /home/soja/AVIANS_ROS2"
echo "rm -rf build/mission_action_modules build/neural_network_detector install/mission_action_modules install/neural_network_detector"
echo ""
echo "========== 步骤 3: 重新编译 =========="
echo "colcon build --packages-select mission_action_modules manual_mission_planner neural_network_detector --symlink-install"
echo ""
echo "========== 步骤 4: Source 环境 =========="
echo "source install/setup.bash"
echo ""
echo "========== 步骤 5: 测试参数服务 =========="
echo "# 启动系统后，运行以下命令测试："
echo "ros2 param get /yolo12_detector_node desired_class"
echo "ros2 param set /yolo12_detector_node desired_class 2"
echo "ros2 param get /yolo12_detector_node desired_class"
echo ""
echo "========== 步骤 6: 查看日志 =========="
echo "# 应该能看到:"
echo "# [yolo12_detector_node]: Runtime parameter update: desired_class changed to 2"
